Sizes bug fixed
rtsc8/hostal_donde_las_paisas pull request #38
Opened 2019-06-24 18:10 UTC by hanna446

I solved the bug of the sizes, adding to SM option and another MD to desktop view.

2019-06-24 18:21 UTC, Sonny97 commented
Could you change the name of this PR by the name of your branch? 'bugfix/button-component-sizing'

2019-06-26 23:38 UTC, jusk02 approved these changes

2019-06-27 19:40 UTC, jhonatanrojasbastidas approved these changes

2019-07-01 16:39 UTC, jusk02 requested changes
please remove all size related rules from the `button` class, and create a `button--lg` block for desktop with the correct sizing

2019-07-01 18:35 UTC, jusk02 approved these changes

2019-07-01 19:26 UTC, merged